# Generated by Django 4.1 on 2022-08-08 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0002_alter_animal_sex"),
    ]

    operations = [
        migrations.RenameField(
            model_name="animal",
            old_name="groups",
            new_name="group",
        ),
    ]
