# Generated by Django 4.1 on 2022-08-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_alter_group_name_alter_group_scientific_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="scientific_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
